### ISSUE TITLE
KM scenarios

### ISSUE THREAD

**Issue by dluc** [freemindlabsinc/FreeMindLabs.KernelMemory.Elasticsearch#28]
I'm logging these under the same issue, not sure these are all covered:

1. as a user, when listing indexes, I should see only KM indexes
  * In Postgres we achieve this by automatically adding a "km-" prefix to DB tables used by KM, so other tables are ignored
  * as a user, I should never see the "km-" prefix, unless I dig into storage directly. E.g. GetIndexesAsync should return the original names
2. as a user, when deleting an index, I cannot delete a non-KM index
  * since ES can contain other user data, it's critical that KM.DeleteIndexAsync cannot be used to delete non-KM data   
3. when upserting a memory record, the corresponding index is created automatically if missing (no errors/warnings)
4. when an index name is not specified, use "default" (e.g. "km-default")

**Comment by afederici75** [comment]
Thank you, in order:
1. and other about index prefix: all handled when I close #18 

3. "when upserting a memory record, the corresponding index is created automatically if missing". I will check this. My intention was to behave just like you, but I might have not finished that.
4. Same for 'default'

Thanks!

**Comment by afederici75** [comment]
@dluc I added the prefix stuff in #18 / #19 and I think all the above should be fixed. I will add the tests to verify shortly.

**Comment by afederici75** [comment]
@dluc I believe all the issues above are fixed.
The only thing I have a comment on is "when upserting a memory record, the corresponding index is created automatically if missing (no errors/warnings)". If I look at your postgres sample, it does not seem there's any moment in which an index is crated automatically by the connector. From what I remember it seems it's something done at the KernelMemory.ImportDocumentAsync. Am I mistaken? Postgrs code: https://github.com/microsoft/kernel-memory-extension-example/blob/908091648036f9de8e1cf299f6000193ffcb06bb/PostgresMemoryStorage/Db/PostgresDbClient.cs#L299

**Comment by dluc** [comment]
my bad, you're correct. It's the Memory instance, not the MemoryDb instance that creates the index - often I conflate the two classes :-)
